// examples/js_vue_motion/src/App.vue
<script setup>
import init, { MotionPath, TweenBatch, initAnimato } from "@aarambhdevhub/animato-core";
import { ref, onMounted } from "vue";

const transform = ref("translate(0px, 0px)");
const batchValue = ref(0);

onMounted(async () => {
  await init();
  initAnimato();
  const motion = MotionPath.line(0, 0, 300, 64, 1);
  const batch = new TweenBatch();
  batch.push(0, 1, 1, "easeOutCubic");

  function frame() {
    motion.update(1 / 60);
    batch.tick(1 / 60);
    batchValue.value = batch.value(0);
    transform.value = `translate(${motion.x()}px, ${motion.y()}px)`;
    if (!motion.isComplete()) requestAnimationFrame(frame);
  }

  frame();
});
</script>

<template>
  <div class="card" :style="{ transform, opacity: batchValue }" />
</template>

// examples/js_svelte_spring/src/App.svelte
<script>
  import init, { Spring2D, initAnimato } from "@aarambhdevhub/animato-core";

  let x = 0;
  let y = 0;
  let spring;

  async function boot() {
    await init();
    initAnimato();
    spring = new Spring2D(0, 0, 180, 80);
    spring.setTarget(180, 80);
    requestAnimationFrame(tick);
  }

  function tick() {
    spring.update(1 / 60);
    const values = spring.toArray();
    x = values[0];
    y = values[1];
    if (!spring.isSettled()) requestAnimationFrame(tick);
  }

  boot();
</script>

<div class="panel" style:transform={`translate(${x}px, ${y}px)`}></div>
