// examples/js_react_tween/src/App.jsx
import init, { Tween, RafDriver, initAnimato } from "@aarambhdevhub/animato-core";
import { useEffect, useRef, useState } from "react";

export function App() {
  const [x, setX] = useState(0);
  const tweenRef = useRef(null);

  useEffect(() => {
    let frame = 0;
    let cancelled = false;

    async function start() {
      await init();
      initAnimato();
      const tween = new Tween(0, 320, 0.9);
      tween.setEasing("easeOutCubic");
      const driver = new RafDriver();
      driver.addTween(tween);
      tweenRef.current = tween;

      function tick(now) {
        if (cancelled) return;
        driver.tick(now);
        setX(tween.value());
        if (!tween.isComplete()) frame = requestAnimationFrame(tick);
      }

      frame = requestAnimationFrame(tick);
    }

    start();
    return () => {
      cancelled = true;
      cancelAnimationFrame(frame);
    };
  }, []);

  return <div className="ball" style={{ transform: `translateX(${x}px)` }} />;
}

// examples/js_vue_motion/src/App.vue
<script setup>
import init, { MotionPath, TweenBatch, initAnimato } from "@aarambhdevhub/animato-core";
import { ref, onMounted } from "vue";

const transform = ref("translate(0px, 0px)");
const batchValue = ref(0);

onMounted(async () => {
  await init();
  initAnimato();
  const motion = MotionPath.line(0, 0, 300, 64, 1);
  const batch = new TweenBatch();
  batch.push(0, 1, 1, "easeOutCubic");

  function frame() {
    motion.update(1 / 60);
    batch.tick(1 / 60);
    batchValue.value = batch.value(0);
    transform.value = `translate(${motion.x()}px, ${motion.y()}px)`;
    if (!motion.isComplete()) requestAnimationFrame(frame);
  }

  frame();
});
</script>

<template>
  <div class="card" :style="{ transform, opacity: batchValue }" />
</template>
